### ISSUE TITLE
Building JavaCC with javaccPlugin

### ISSUE THREAD

**Issue by MehrunesSky** [javacc/javaccPlugin#71]
I have the same problem as #30 

I have this error on rebuild     

error: cannot find symbol
@SneakyThrows(ParseException.class)
                  ^
  symbol:   class ParseException

I have to clean my project on every change on .jj

Do you have already got this issue?

**Comment by MehrunesSky** [comment]
This is my configuration
compileJavacc {
    outputDirectory = file(project.buildDir.absolutePath + '/generated/sources/annotationProcessor/java/main/')
    arguments = [grammar_encoding: 'UTF-8', static: 'false']
}

I work on gradle 8.6

**Comment by zbynek** [comment]
> outputDirectory = file(project.buildDir.absolutePath + '/generated/sources/annotationProcessor/java/main/')

This doesn't look right -- the `build/generated/sources/annotationProcessor` path is managed by the `compileJava` task, which might  clean that folder after JavaCC generated the files.

I'd suggest to either  use the default `outputDirectory` which is effectively `file(project.buildDir.absolutePath + '/generated/javacc')`  or pick something outside of the annotation processor output.
